apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: ghcr.io/smlsoft/dedemerchantreportapi:beta
  imagePullSecrets:
  - name: dockerconfigjson-github-com